### ISSUE TITLE
Makes URL more unique

### ISSUE THREAD

**Issue by gollumnima** [yorkie-team/toonie#10]
**Description**:
```js
export const generateRandomParams = () => {
  return `/${Math.random().toString(36).substring(7)}`;
};
```
In this logic, there will be a risk of duplicate strings.
 

**Why**:
Using `Math.random()` method can make duplicate values. If we change this logic, users can use safer URL. 

**Solutions**:

1. add timestamp in the URL
2. use [nanoid](https://www.npmjs.com/package/nanoid) library 

I want to contribute to this issue and I don't know whether is a better way to solve this issue. 🤔

**Comment by hackerwins** [comment]
@gollumnima Thanks for your suggestion.

The previous approach has a high risk of duplicating keys. I agree with you. It's the first time I've seen `nanoid`, if it's appropriate, I hope it's applied.

**Comment by hunkim98** [comment]
@gollumnima 

Seems like a good idea!
